### ISSUE TITLE
why can't connect？

### ISSUE THREAD

**Issue by LanBaiCode** [ds20211213/frida-ceserver#2]
Here is my config info and problem
![can'tconnect](https://user-images.githubusercontent.com/72244576/157352943-bd783783-4073-4e8a-8702-f7e9ba3e45c5.png)

**Comment by ds20211213** [comment]
Thank you for your comment.
The Cheat Engine is incorrectly configured.

Host:localhost
Port:52736

frida-cesrever automatically connects to Cheat Engine and IOS native ceserver.
![img](https://user-images.githubusercontent.com/96031346/157355186-5e21188d-28ba-44cb-a9db-d737e88682e5.png)

**Comment by LanBaiCode** [comment]
> 
Thank you for your answer, I have successfully connected,but the search speed is too slow, and there will be lags

**Comment by LanBaiCode** [comment]
But there's no denying it's a great project！
This search is very fast, you can refer to the following
https://github.com/rainyx/rxmemscan

**Comment by ds20211213** [comment]
Network->Compression->Level3
Using compression of the memory read process will slightly speed up the process.
Also, prepare a fast wifi environment.
Thank you for posting the reference example of the fast search.
