### ISSUE TITLE
PointerScanning doesn't work sadly

### ISSUE THREAD

**Issue by Thekidiacs** [ds20211213/frida-ceserver#3]
I'm running an iPad air 4th generation on iOS 14.2. I was trying to cheat in a game and I found the values I needed but when I ran the pointerscan on the process "self" it didn't show any results after taking forever to generate the pointermap. I am so happy you created this project because I am praying that you will eventually get the debugger to work as well as pointer scanning. For years I have been hoping for a ceserver port of the real "Cheat Engine" on iOS. I hope you can maybe help me with this as I really think this is awesome what you made!

**Comment by ds20211213** [comment]
Sorry for the late reply.
Thank you for your comment.
Is process memory being read?
It may be a static judgment issue. Please try once with the image settings.
A simple watchpoint via lldb will be implemented soon.

![125820803-038d5cbf-19b8-47a8-9caf-0ba8b470406b](https://user-images.githubusercontent.com/96031346/163502010-9931d4e1-557d-460c-a552-06ec52ca59bb.png)

**Comment by Thekidiacs** [comment]
Okay I'm going to do it now and report back!

**Comment by Thekidiacs** [comment]
Great news! It works! Thank you so much! I already have a pointer for the game I need. Before I close this thread I have a question. Will you ever be able to get the debugger to work? This would easily make your cheat engine better than anything on iOS. There is no cheat engine on iOS that has string scan that I'm aware of. But this one has it because its the real cheat engine lol. I hope one day you'll be able to get the debugger to work.

**Comment by ds20211213** [comment]
Since the cheat engine does not currently support arm64, I am not considering a debugger that would step through the program one instruction at a time.
As for watchpoint, I think it is possible by running debugserver directly, and I hope to realize the "find out what accesses this address" function.
I believe that is possible in the near future.

**Comment by Thekidiacs** [comment]
My favorite debug feature hands down is "find out what accesses to this address" and "find out what writes to this address". With this lldb feature that you plan on implementing will you be able to find what accesses the address and writes? That would be great if so.

**Comment by ds20211213** [comment]
I have successfully set up a hardware watch point from the cheat engine gui at this point. (memory read/memory write/memory access)
However, cheat engine does not support arm64, so I need to create a separate gui.

**Comment by ds20211213** [comment]
Debugger support has been added, albeit partial.
